/**
 * Unified GIF Registry System
 * 
 * Single source of truth for exercise-to-GIF mappings that:
 * - Discovers GIFs from filesystem
 * - Provides intelligent filename-based matching
 * - Integrates admin approval status
 * - Maintains high performance with O(1) lookups
 */

import { ExerciseMatchingEngine, ExerciseContext, ExerciseMatchResult } from '../utils/exerciseMatching'
import { filenameToExerciseName, extractCategoryFromPath } from '../utils/filenameNormalization'
import { api } from './api'

export interface GifRegistryEntry {
  id: string
  exerciseName: string
  gifPath: string
  filename: string
  category: string
  approvalStatus: 'approved' | 'pending' | 'flagged' | 'hidden'
  lastReviewedAt?: Date
  reviewedBy?: string
  flaggedReason?: string
  confidence: number
  matchType: string
  isAutoGenerated: boolean
  fileSize?: number
  lastModified?: Date
}

export interface DiscoveredGifFile {
  filename: string
  path: string
  category: string
  fileSize: number
  lastModified: Date
}

interface AdminApprovalData {
  exerciseId: string
  approvalStatus: 'approved' | 'pending' | 'flagged' | 'hidden'
  reviewedBy?: string
  flaggedReason?: string
  lastReviewedAt?: Date
}

/**
 * Unified GIF Registry - Single source of truth for exercise-GIF mappings
 */
export class UnifiedGifRegistry {
  private static instance: UnifiedGifRegistry | null = null
  
  private registry = new Map<string, GifRegistryEntry>()
  private exerciseToGifMap = new Map<string, string>() // Fast lookup: exerciseName → gifPath
  private matchingEngine = new ExerciseMatchingEngine()
  private discoveredGifs: DiscoveredGifFile[] = []
  private isInitialized = false
  private initializationPromise: Promise<void> | null = null
  
  // Cache management
  private lastDiscoveryTime = 0
  private discoveryInterval = 5 * 60 * 1000 // 5 minutes
  private adminApprovalCache = new Map<string, AdminApprovalData>()
  
  private constructor() {
    // Private constructor for singleton
  }
  
  /**
   * Get singleton instance
   */
  static getInstance(): UnifiedGifRegistry {
    if (!UnifiedGifRegistry.instance) {
      UnifiedGifRegistry.instance = new UnifiedGifRegistry()
    }
    return UnifiedGifRegistry.instance
  }
  
  /**
   * Initialize the registry (discover GIFs and build mappings)
   */
  async initialize(forceRefresh = false): Promise<void> {
    if (this.isInitialized && !forceRefresh && this.initializationPromise) {
      return this.initializationPromise
    }
    
    this.initializationPromise = this._performInitialization(forceRefresh)
    
    try {
      await this.initializationPromise
      this.isInitialized = true
      console.log(`✅ UnifiedGifRegistry initialized successfully: ${this.registry.size} entries`)
    } catch (error) {
      console.error('❌ Failed to initialize UnifiedGifRegistry:', error)
      this.initializationPromise = null
      // Don't throw - instead mark as initialized with empty state to prevent blocking
      this.isInitialized = true
      console.warn('🔄 Registry initialized with empty state due to errors')
    }
  }
  
  /**
   * Perform the actual initialization process
   */
  private async _performInitialization(forceRefresh = false): Promise<void> {
    console.log('🎬 Initializing Unified GIF Registry...')
    
    try {
      // Step 1: Discover available GIF files
      await this.discoverGifFiles(forceRefresh)
      
      // Step 2: Load admin approval data
      await this.loadAdminApprovals()
      
      // Step 3: Build registry entries
      this.buildRegistryEntries()
      
      // Step 4: Initialize matching engine
      this.matchingEngine.setAvailableGifs(
        this.discoveredGifs.map(gif => ({
          filename: gif.filename,
          path: gif.path
        }))
      )
      
      console.log(`✅ GIF Registry initialized with ${this.registry.size} entries`)
      console.log(`📊 Stats:`, this.getRegistryStats())
      
    } catch (error) {
      console.error('❌ Failed to initialize GIF Registry:', error)
      throw error
    }
  }
  
  /**
   * Discover available GIF files from the filesystem/API
   */
  private async discoverGifFiles(forceRefresh = false): Promise<void> {
    const now = Date.now()
    
    if (!forceRefresh && 
        this.discoveredGifs.length > 0 && 
        (now - this.lastDiscoveryTime) < this.discoveryInterval) {
      return // Use cached discovery
    }
    
    try {
      // Call public API to get available GIF files with increased timeout
      const response = await api.get('/api/gif-files', {
        skipErrorToast: true,
        timeout: 10000 // 10 second timeout instead of default
      })
      
      this.discoveredGifs = response.data.map((gif: any) => ({
        filename: gif.filename,
        path: gif.path,
        category: extractCategoryFromPath(gif.path),
        fileSize: gif.size || 0,
        lastModified: new Date(gif.lastModified || Date.now())
      }))
      
      this.lastDiscoveryTime = now
      console.log(`🔍 Discovered ${this.discoveredGifs.length} GIF files from API`)
      
    } catch (error) {
      console.warn('⚠️ Failed to discover GIF files from API, using comprehensive fallback:', error)
      
      // Enhanced fallback: try to discover GIFs locally first, then use hardcoded list
      try {
        this.discoveredGifs = await this.getComprehensiveFallbackGifList()
        console.log(`📂 Using comprehensive fallback: ${this.discoveredGifs.length} GIF files`)
      } catch (fallbackError) {
        console.error('❌ Comprehensive fallback failed, using minimal fallback:', fallbackError)
        this.discoveredGifs = this.getFallbackGifList()
        console.log(`🔄 Using minimal fallback: ${this.discoveredGifs.length} GIF files`)
      }
    }
  }
  
  /**
   * Load admin approval data from the backend
   */
  private async loadAdminApprovals(): Promise<void> {
    try {
      const response = await api.get('/api/admin/exercise-approvals', {
        skipErrorToast: true
      })
      
      this.adminApprovalCache.clear()
      
      for (const approval of response.data) {
        this.adminApprovalCache.set(approval.exerciseId, approval)
      }
      
      console.log(`📋 Loaded ${this.adminApprovalCache.size} admin approvals`)
      
    } catch (error) {
      console.warn('⚠️ Failed to load admin approvals - continuing with defaults:', error)
      // Continue without admin approvals - will default to 'pending'
      // This ensures the registry still works even if admin approval API fails
    }
  }
  
  /**
   * Build registry entries from discovered GIFs and admin approvals
   */
  private buildRegistryEntries(): void {
    this.registry.clear()
    this.exerciseToGifMap.clear()
    
    for (const gif of this.discoveredGifs) {
      const exerciseName = filenameToExerciseName(gif.filename)
      const exerciseId = `${exerciseName.toLowerCase().replace(/\s+/g, '_')}_${gif.category}`
      
      // Get admin approval status
      const approval = this.adminApprovalCache.get(exerciseId)
      const approvalStatus = approval?.approvalStatus || 'pending'
      
      // Skip hidden GIFs unless admin is viewing
      if (approvalStatus === 'hidden') {
        continue
      }
      
      const entry: GifRegistryEntry = {
        id: exerciseId,
        exerciseName,
        gifPath: gif.path,
        filename: gif.filename,
        category: gif.category,
        approvalStatus,
        lastReviewedAt: approval?.lastReviewedAt,
        reviewedBy: approval?.reviewedBy,
        flaggedReason: approval?.flaggedReason,
        confidence: 1.0, // Direct filename match
        matchType: 'filename_direct',
        isAutoGenerated: true,
        fileSize: gif.fileSize,
        lastModified: gif.lastModified
      }
      
      this.registry.set(exerciseId, entry)
      
      // Only add to lookup map if approved or pending
      if (approvalStatus === 'approved' || approvalStatus === 'pending') {
        this.exerciseToGifMap.set(exerciseName.toLowerCase(), gif.path)
      }
    }
  }
  
  /**
   * Get GIF path for an exercise with intelligent matching
   */
  async getExerciseGif(
    exerciseName: string, 
    context?: ExerciseContext,
    includeUnapproved = false
  ): Promise<string | null> {
    if (!this.isInitialized) {
      await this.initialize()
    }
    
    // Try fast lookup first (for approved/pending exercises)
    const normalizedName = exerciseName.toLowerCase().trim()
    const quickMatch = this.exerciseToGifMap.get(normalizedName)
    
    if (quickMatch) {
      return quickMatch
    }
    
    // Use intelligent matching engine for complex cases
    const matchResult = this.matchingEngine.findBestMatch(exerciseName, context)
    
    if (!matchResult.gifPath) {
      return null
    }
    
    // Check approval status of matched GIF
    const matchedEntry = Array.from(this.registry.values()).find(entry => 
      entry.gifPath === matchResult.gifPath
    )
    
    if (!matchedEntry) {
      return matchResult.gifPath // Fallback
    }
    
    // Respect approval status
    const isApproved = matchedEntry.approvalStatus === 'approved'
    const isPending = matchedEntry.approvalStatus === 'pending'
    const isFlagged = matchedEntry.approvalStatus === 'flagged'
    
    if (isApproved || (includeUnapproved && (isPending || isFlagged))) {
      return matchResult.gifPath
    }
    
    return null // Not approved for user view
  }
  
  /**
   * Get detailed match information for admin/debugging purposes
   */
  async getExerciseMatchDetails(
    exerciseName: string, 
    context?: ExerciseContext
  ): Promise<ExerciseMatchResult & { registryEntry?: GifRegistryEntry }> {
    if (!this.isInitialized) {
      await this.initialize()
    }
    
    const matchResult = this.matchingEngine.findBestMatch(exerciseName, context)
    
    // Find the registry entry for additional details
    let registryEntry: GifRegistryEntry | undefined
    if (matchResult.gifPath) {
      registryEntry = Array.from(this.registry.values()).find(entry => 
        entry.gifPath === matchResult.gifPath
      )
    }
    
    return {
      ...matchResult,
      registryEntry
    }
  }
  
  /**
   * Get all registry entries (for admin dashboard)
   */
  getAllEntries(filterStatus?: string): GifRegistryEntry[] {
    const entries = Array.from(this.registry.values())
    
    if (!filterStatus || filterStatus === 'all') {
      return entries
    }
    
    return entries.filter(entry => entry.approvalStatus === filterStatus)
  }
  
  /**
   * Update approval status (called by admin dashboard)
   */
  async updateApprovalStatus(
    exerciseId: string, 
    approvalStatus: 'approved' | 'pending' | 'flagged' | 'hidden',
    reviewedBy?: string,
    flaggedReason?: string
  ): Promise<boolean> {
    try {
      // Update backend
      await api.patch(`/api/admin/exercise-approval/${exerciseId}`, {
        approvalStatus,
        reviewedBy,
        flaggedReason,
        lastReviewedAt: new Date().toISOString()
      })
      
      // Update local cache
      this.adminApprovalCache.set(exerciseId, {
        exerciseId,
        approvalStatus,
        reviewedBy,
        flaggedReason,
        lastReviewedAt: new Date()
      })
      
      // Rebuild registry to reflect changes
      this.buildRegistryEntries()
      
      console.log(`✅ Updated approval status for ${exerciseId}: ${approvalStatus}`)
      return true
      
    } catch (error) {
      console.error(`❌ Failed to update approval status for ${exerciseId}:`, error)
      return false
    }
  }
  
  /**
   * Refresh the registry (re-discover GIFs and reload approvals)
   */
  async refresh(): Promise<void> {
    console.log('🔄 Refreshing GIF Registry...')
    await this.initialize(true)
  }
  
  /**
   * Get registry statistics
   */
  getRegistryStats(): {
    totalEntries: number
    approvalStatusCounts: Record<string, number>
    categoryCounts: Record<string, number>
    matchingStats: any
  } {
    const approvalStatusCounts: Record<string, number> = {}
    const categoryCounts: Record<string, number> = {}
    
    for (const entry of this.registry.values()) {
      approvalStatusCounts[entry.approvalStatus] = 
        (approvalStatusCounts[entry.approvalStatus] || 0) + 1
      
      categoryCounts[entry.category] = 
        (categoryCounts[entry.category] || 0) + 1
    }
    
    return {
      totalEntries: this.registry.size,
      approvalStatusCounts,
      categoryCounts,
      matchingStats: this.matchingEngine.getMatchingStats()
    }
  }
  
  /**
   * Comprehensive fallback GIF discovery using browser-based scanning
   */
  private async getComprehensiveFallbackGifList(): DiscoveredGifFile[] {
    // Since we're in the browser, we can't directly scan the filesystem
    // But we can try to systematically check for known GIF files
    const categories = ['warmup', 'cardio', 'strength', 'core', 'legs', 'arms', 'back', 'chest', 'shoulders', 'full-body'];
    const discoveredGifs: DiscoveredGifFile[] = [];
    
    // Try to fetch the directory listing via a different approach
    try {
      // First try to get a comprehensive list from the public directory structure
      // This would require a different API endpoint that doesn't require admin auth
      const response = await fetch('/exercise-gifs/', { method: 'GET' });
      if (response.ok) {
        // Parse directory listing if available (this might not work in all setups)
        const text = await response.text();
        // This is a fallback attempt - may not work in production
      }
    } catch (fetchError) {
      // If direct access fails, fall back to known file patterns
    }
    
    // Generate comprehensive list based on known patterns from filesystem
    return this.generateKnownGifList();
  }
  
  /**
   * Generate a comprehensive list of known GIFs based on filesystem analysis
   */
  private generateKnownGifList(): DiscoveredGifFile[] {
    const knownGifs: Array<{filename: string, path: string, category: string}> = [];
    
    // Add all warmup GIFs we created
    const warmupGifs = [
      'arm-circles.gif', 'shoulder-rolls.gif', 'walking-lunge.gif', 'torso-twists.gif',
      'hip-circles.gif', 'walking-high-knees.gif', 'butt-kickers.gif', 'leg-swings.gif',
      'ankle-circles.gif', 'neck-rolls.gif', 'wrist-circles.gif', 'marching-in-place.gif',
      'gentle-jumping-jacks.gif', 'body-weight-squats.gif', 'forward-arm-swings.gif'
    ];
    warmupGifs.forEach(filename => {
      knownGifs.push({
        filename,
        path: `/exercise-gifs/warmup/${filename}`,
        category: 'warmup'
      });
    });
    
    // Add cardio GIFs
    const cardioGifs = [
      'jack-burpee.gif', 'mountain-climber.gif', 'walking-high-knees-lunge.gif'
    ];
    cardioGifs.forEach(filename => {
      knownGifs.push({
        filename,
        path: `/exercise-gifs/cardio/${filename}`,
        category: 'cardio'
      });
    });
    
    // Add core GIFs (sample of known files from directory listing)
    const coreGifs = [
      '34-sit-up.gif', '45-side-bend.gif', 'air-bike.gif', 'alternate-heel-touchers.gif',
      'front-plank-with-twist.gif', 'bottoms-up.gif', 'cable-kneeling-crunch.gif'
    ];
    coreGifs.forEach(filename => {
      knownGifs.push({
        filename,
        path: `/exercise-gifs/core/${filename}`,
        category: 'core'
      });
    });
    
    // Add legs GIFs (sample of known files)
    const legsGifs = [
      'barbell-lunge.gif', 'barbell-full-squat.gif', 'barbell-deadlift.gif',
      'barbell-front-squat.gif', 'barbell-romanian-deadlift.gif', 'barbell-step-up.gif'
    ];
    legsGifs.forEach(filename => {
      knownGifs.push({
        filename,
        path: `/exercise-gifs/legs/${filename}`,
        category: 'legs'
      });
    });
    
    // Add arms GIFs (sample of known files)
    const armsGifs = [
      'barbell-curl.gif', 'barbell-close-grip-bench-press.gif', 'cable-pushdown.gif',
      'biceps-pull-up.gif', 'weighted-tricep-dips.gif'
    ];
    armsGifs.forEach(filename => {
      knownGifs.push({
        filename,
        path: `/exercise-gifs/arms/${filename}`,
        category: 'arms'
      });
    });
    
    // Add back GIFs
    const backGifs = [
      'barbell-bent-over-row.gif', 'barbell-shrug.gif', 'pull-up-neutral-grip.gif',
      'cable-seated-wide-grip-row.gif', 'assisted-pull-up.gif'
    ];
    backGifs.forEach(filename => {
      knownGifs.push({
        filename,
        path: `/exercise-gifs/back/${filename}`,
        category: 'back'
      });
    });
    
    // Add chest GIFs
    const chestGifs = [
      'barbell-bench-press.gif', 'barbell-incline-bench-press.gif', 'barbell-decline-bench-press.gif',
      'cable-cross-over-variation.gif', 'incline-push-up-depth-jump.gif'
    ];
    chestGifs.forEach(filename => {
      knownGifs.push({
        filename,
        path: `/exercise-gifs/chest/${filename}`,
        category: 'chest'
      });
    });
    
    // Add shoulders GIFs
    const shouldersGifs = [
      'barbell-front-raise.gif', 'barbell-upright-row.gif', 'barbell-seated-overhead-press.gif',
      'cable-lateral-raise.gif', 'battling-ropes.gif'
    ];
    shouldersGifs.forEach(filename => {
      knownGifs.push({
        filename,
        path: `/exercise-gifs/shoulders/${filename}`,
        category: 'shoulders'
      });
    });
    
    return knownGifs.map(gif => ({
      ...gif,
      fileSize: 0,
      lastModified: new Date()
    }));
  }

  /**
   * Fallback GIF list when API discovery fails
   */
  private getFallbackGifList(): DiscoveredGifFile[] {
    // Based on the known directory structure from our analysis
    const fallbackGifs = [
      // Cardio
      { filename: 'mountain-climber.gif', path: '/exercise-gifs/cardio/mountain-climber.gif', category: 'cardio' },
      { filename: 'walking-high-knees-lunge.gif', path: '/exercise-gifs/cardio/walking-high-knees-lunge.gif', category: 'cardio' },
      { filename: 'jack-burpee.gif', path: '/exercise-gifs/cardio/jack-burpee.gif', category: 'cardio' },
      
      // Core
      { filename: 'front-plank-with-twist.gif', path: '/exercise-gifs/core/front-plank-with-twist.gif', category: 'core' },
      { filename: 'air-bike.gif', path: '/exercise-gifs/core/air-bike.gif', category: 'core' },
      
      // Legs
      { filename: 'barbell-lunge.gif', path: '/exercise-gifs/legs/barbell-lunge.gif', category: 'legs' },
      { filename: 'barbell-squat.gif', path: '/exercise-gifs/legs/barbell-full-squat.gif', category: 'legs' },
      
      // Arms
      { filename: 'barbell-curl.gif', path: '/exercise-gifs/arms/barbell-curl.gif', category: 'arms' },
      
      // Back
      { filename: 'barbell-bent-over-row.gif', path: '/exercise-gifs/back/barbell-bent-over-row.gif', category: 'back' },
      
      // Chest
      { filename: 'barbell-bench-press.gif', path: '/exercise-gifs/chest/barbell-bench-press.gif', category: 'chest' },
      
      // Shoulders
      { filename: 'barbell-front-raise.gif', path: '/exercise-gifs/shoulders/barbell-front-raise.gif', category: 'shoulders' }
    ]
    
    return fallbackGifs.map(gif => ({
      ...gif,
      fileSize: 0,
      lastModified: new Date()
    }))
  }
  
  /**
   * Clear all caches and reset (for testing/development)
   */
  reset(): void {
    this.registry.clear()
    this.exerciseToGifMap.clear()
    this.adminApprovalCache.clear()
    this.discoveredGifs = []
    this.isInitialized = false
    this.initializationPromise = null
    this.lastDiscoveryTime = 0
  }
}

// Export singleton instance
export const unifiedGifRegistry = UnifiedGifRegistry.getInstance()